kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0add61f0ed0022fc7
    fsType: ext4